[versions]
android-plugin = "8.5.2"
jetbrains-kotlin-plugin = "2.0.21"
jetbrains-compose-plugin = "1.7.0"

androidx-appcompat = "1.7.0"
androidx-activity = "1.9.3"

[plugins]
android-application = { id = "com.android.application", version.ref = "android-plugin" }
jetbrains-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrains-kotlin-plugin" }
jetbrains-compose = { id = "org.jetbrains.compose", version.ref = "jetbrains-compose-plugin" }
jetbrains-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrains-kotlin-plugin" }

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }